jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [ '2.x', '3.x']
        os: ['windows-latest', 'ubuntu-latest']
    name: Python ${{ matrix.python }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: "Download test assets"
        run: bash ci/travis_downloaddata.sh
      - name: "Run Tests"
        run: make testall
