# largely taken from
# https://raw.githubusercontent.com/pydata/pandas/master/appveyor.yml
# https://bitbucket.org/pygame/pygame/pull-requests/45/create-python-wheel-builds-using-appveyor/diff

matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  pypi_password:
    secure: MT+Dz2JEdUGkHuJr7LW3qA==
  pypi_username:
    secure: NnjqwC7S1x2ImdY12RoVjg==

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"
    DISTRIBUTIONS: "bdist_wheel"

  matrix:
    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "110"

build: off

# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable (which is used by CMD_IN_ENV).
platform:
    - x64

init:
  - "ECHO %PYTHON_VERSION% %PYTHON%"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  - powershell .\ci\install.ps1
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - echo "install"
  - cd
  - ls -ltr
  - git tag --sort v:refname

  # install our build environment
  - cmd: conda config --set show_channel_urls yes --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda config --set ssl_verify false

  # this is now the downloaded conda...
  - conda info -a

  # build em using the local source checkout in the correct windows env
  - conda install conda-build

  # create our env
  - cmd: conda create -q -n pyquant python=%PYTHON_VERSION% nose pandas scipy cython lxml scikit-learn patsy
  - cmd: activate pyquant
  - cmd: pip install git+git://github.com/pandeylab/pythomics.git
  - cmd: pip install wheel
  #- ps: conda install -q (conda build conda.recipe -q --output --no-test)
  - cmd: set HOME=%APPVEYOR_BUILD_FOLDER%
  - cmd: '%CMD_IN_ENV% python.exe setup.py build'
  - cmd: '%CMD_IN_ENV% python.exe setup.py build_ext --inplace'

test_script:
  # tests
  - pip freeze
  - ls -ltr

after_test:
  - "python.exe setup.py %DISTRIBUTIONS%"

artifacts:
  - path: dist\*

deploy_script:
  - cmd: "echo [server-login] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: %pypi_username% >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %pypi_password% >> %USERPROFILE%\\.pypirc"
  - cmd: "python.exe setup.py bdist_wheel upload"