version: '2.1'

services:
  pyquant:
    image: pyquant:dev
    build: .
    environment:
      PYQUANT_DEV: True
    volumes:
      - ./data:/data
      - ./tests:/pyquant/tests
      - ./pyquant:/pyquant/pyquant
