#!/usr/bin/env python
from pyquant import pyquant_parser
from pyquant.command_line import run_pyquant
import sys, signal

parser = pyquant_parser

if __name__ == '__main__':
    try:
        run_pyquant()
    except KeyboardInterrupt:
        signal.signal(signal.SIGTERM, lambda signum, stack_frame: sys.exit(1))