package:
    name: pyquant
    version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('.dev', 'dev') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    path: ../../

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - libpython # [py2k and win]
    - setuptools
    - pandas
    - scikit-learn
    - patsy
    - pythomics

  run:
    - python
    - cython
    - numpy x.x
    - libpython # [py2k and win]
    - setuptools
    - pandas
    - scikit-learn
    - patsy
    - pythomics

test:
  imports:
    - pyquant

about:
  home: https://github.com/Chris7/pyquant
  license: MIT
